#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Avocado"
  https://create.arduino.cc/cloud/things/28119d40-7b07-4e6f-ade9-e1861e100be2 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float temperature;
  int moisture;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
// Arduino_MKRENV - Version: Latest
// https://script.google.com/macros/s/AKfycbxY9otOmTiLqmFTywLgirJ3LJkmNOr3f5iX2g3LKvBmqsqGyBA/exec



#include "env.h"
#include "play.h"
#include "iot.h"
#define UPDATE_INTERVAL 60000

bool awake = true;

void setup() {
  Serial.begin(9600);
  delay(1000);
  setupUno();
  setupENV();
  setupIOT();
}

void setupUno() {
  setupPlay();
}


void loop() {
  int moisture = readMoisture();
  updateIOT(readTemperature(), moisture);
  goToSleep();

}

void goToSleep() {
  delay(UPDATE_INTERVAL);
}

































